
version: '3.8'
services:
  bot:
    build: .
    container_name: stb-bot-cli
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_USERNAME=${OWNER_USERNAME}
      - REQUIRED_CHANNEL=${REQUIRED_CHANNEL}
      - CHANNEL_ID=${CHANNEL_ID}
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./downloads:/app/downloads
    networks:
      - net
networks:
  net:
