version: '3.8'

services:
  bot:
    build: .
    container_name: stb-bot-final
    restart: unless-stopped
    privileged: true
    user: "0:0"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_USERNAME=${OWNER_USERNAME}
      - REQUIRED_CHANNEL=${REQUIRED_CHANNEL}
      - CHANNEL_ID=${CHANNEL_ID}
      - AUTO_CLEANUP_ENABLED=true
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
