version: '3.8'

services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: telegram-bot-stb-bullseye
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-8436081597:AAE-8bfWrbvhl26-l9y65p48DfWjQOYPR2A}
      - BOT_USERNAME=${BOT_USERNAME}
      - OWNER_USERNAME=${OWNER_USERNAME:-zalhera}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID:-root}
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-2}
      - MAX_SPEED_MBPS=${MAX_SPEED_MBPS:-15}
      - CHUNK_SIZE=${CHUNK_SIZE:-8192}
      - OAUTH_PORT=${OAUTH_PORT:-8080}
      - ARIA2_SECRET=${ARIA2_SECRET:-bullseye_secret}
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./credentials:/app/credentials
      - ./torrents:/app/torrents
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
    ports:
      - "${OAUTH_PORT:-8080}:8080"
    networks:
      - stb-network
    depends_on:
      - aria2
    privileged: true
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  aria2:
    image: p3terx/aria2-pro:latest
    container_name: aria2-stb-bullseye
    restart: unless-stopped
    logging:
      driver: none
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=${ARIA2_SECRET:-bullseye_secret}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - TZ=Asia/Jakarta
    volumes:
      - ./aria2-config:/config
      - ./downloads:/downloads
      - ./torrents:/app/torrents
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    networks:
      - stb-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  stb-network:
    driver: bridge
